### ISSUE TITLE
Multiple language support for the animation video

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-marketing#141]
Please do not publish until it is marked as ready for release. 

We should support multiple languages for the animation video, based on the English captions here: https://github.com/w3c/wot-marketing/blob/master/videos/WoT-Explainer-Video/WOTMotion.en.vtt

- [x] Japanese (@ashimura and @k-toumura & @chachamimm (for review); RELEASED) --> PR #165
- [x] German (@sebastiankb and @danielpeintner (for review); ready for RELEASE) --> PR #167
- [x] Italian (@relu91  and @danielpeintner (for review); RELEASED)--> PR #147 merged
- [x] Chinese (@lmy441900 and @siusin; RELEASED) --> PR #149 merged
- [x] French (@koalie and @vcharpenay (for review); ready for RELEASE) --> PR #152 available
- [x] Spanish (@AndreaCimminoArriaga and @agmangas (for review); ready for RELEASE) --> PR #181

**Comment by relu91** [comment]
count on me for Italian!👍

**Comment by egekorkan** [comment]
Could you provide srt file for english?

**Comment by koalie** [comment]
> Could you provide srt file for english?

I believe it's available in the [mail](https://lists.w3.org/Archives/Team/team-wot/2021Feb/0029.html) @ashimura sent on 16-Feb

**Comment by koalie** [comment]
> Could you provide srt file for english?

Here: https://github.com/w3c/wot-marketing/issues/141#issuecomment-788912494

**Comment by koalie** [comment]
> Could you provide srt file for english?

Here: https://github.com/w3c/wot-marketing/blob/master/videos/WoT-Explainer-Video/WOTMotion.en.vtt

**Comment by lmy441900** [comment]
Wonder if @sebastiankb has found any Chinese translator? If not I'm very happy to translate the subtitles into (Simplified) Chinese.

**Comment by sebastiankb** [comment]
@AndreaCimminoArriaga would it be possible for you to provide a Spanish caption version? would be great.

**Comment by AndreaCimminoArriaga** [comment]
Hi @sebastiankb, sorry for the late reply. Count me in for the Spanish ;)

**Comment by sebastiankb** [comment]
From today's marketing call: The group like to decide when we publish the subtitles. We still waiting for the Spanish version. The German version have not been published yet.

**Comment by sebastiankb** [comment]
from today's marketing call:
- we have all requested languages
- @dontcallmedom would be great to publish all marked "ready to RELEASE" (german, french and spanish) at youtube

**Comment by lmy441900** [comment]
Note that there is still an unfixed overlap in entry 35 - 37. I've created PR #182 fixing this. In addition, there are still wording errors in the English version (subtitles do not match the voice). Better fix them too.

**Comment by sebastiankb** [comment]
@lmy441900 many thanks for the hint. Indeed, this is a bug. The sentence "The TD is comparable to an index.html for Things." is not showing up. I will quickly merge your PR so this will be available for the release.

**Comment by sebastiankb** [comment]
@dontcallmedom du to the PR #182 we need to update all languages again. I hope this is ok for you.

**Comment by sebastiankb** [comment]
@dontcallmedom may I ask about the status (please see comment [here](https://github.com/w3c/wot-marketing/issues/141#issuecomment-847780649))? many thanks

**Comment by dontcallmedom** [comment]
I was off last week - I've now uploaded the captions on youtube, let me know if anything is amiss. 

@ashimura can you send me your Google account? that way you should be able to deal with these updates directly

**Comment by sebastiankb** [comment]
@dontcallmedom many thanks! 

will close the issue
