### ISSUE TITLE
Netlify Open Source License Checklist

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-marketing#304]
I have learned from the system team that they cannot share their license and that we should apply for an open source plan at Netlify. The details are at https://www.netlify.com/legal/open-source-policy and I am putting them below here (adding numbers for easier discussion):

- [x] 1. Includes a license listed on the [Open Source Initiative approved license list](https://opensource.org/licenses) or a [Creative Commons license](https://creativecommons.org/choose/) that includes “attribution” or places the work in the [public domain](https://creativecommons.org/publicdomain/).

- [x] 2. Features a [Code of Conduct](https://projectinclude.org/writing_cocs) at the top level directory of the project repository or prominently in the documentation (with a link in the navigation, footer, or homepage).

- [x] 3. Must feature a link to our service on your main page, or all internal pages. You have two options:
  - We have [premade badges](https://www.netlify.com/press/#badges) for your convenience, or
  -  You may create your own link, which should read “This site is powered by Netlify”, and include a link back to our home page.
    
- [x] 4. Must not be a commercial project, whether created by a company or an individual. This prohibition includes commercial support and hosting services.

**Comment by egekorkan** [comment]
Call of 12.04:
- @relu91 : Regarding point 3, we can simply add some environment variables to show the badge or link when the site is deployed via netlify and not not show it when it is deployed on github
- @ashimura : since this means applying for the license as the WoT Marketing TF and not personally, we should talk with the systems team and the WG Chairs

**Comment by egekorkan** [comment]
I have done item 1 and 2 in the PR #312 . Point 3 is also taken care of now in the site settings by doing a snippet injection. At the bottom of the page, we can see the netlify badge. To see it live, go to https://wot-marketing.netlify.app/

Once the PR is merged, I will do ask for the license

**Comment by egekorkan** [comment]
PR is merged, @egekorkan is going to ask for the license now

**Comment by egekorkan** [comment]
I have obtained a new team that is open source approved and we can add more team members (not sure about the limit). I have added the WoT WG/IG chairs @mmccool and @sebastiankb , @danielpeintner since he contributes to the websites and @relu91 since he is the co chair of WoT CG. 
https://app.netlify.com/teams/sponsored-oss-account-tdgovmm/overview is the link but it needs login first

**Comment by egekorkan** [comment]
Also here is the email I had received:

> Thanks, that looks good to me!
 
> You can find your new sponsored team here:
 
> https://app.netlify.com/teams/sponsored-oss-account-tdgovmm/overview
 
> Please note that while this is a free account, it is not an unlimited account - please carefully review the limitations for the paid Pro plan here: https://www.netlify.com/pricing/#teams - your project will still be financially liable for overages in bandwidth, build minutes, form submissions, and the like above the Pro plan limits (except for contributors, which are unlimited on the sponsored plan).
 
> Now that you have access to the team, you'll probably want to [invite your collaborators to the team](https://docs.netlify.com/accounts-and-billing/team-management/manage-team-members/#add-new-team-members) as well.
 
> You can transfer your existing site to that team following this workflow: https://docs.netlify.com/accounts-and-billing/team-management/team-owned-sites/#transfer-sites-between-teams - but do keep in mind we intend this team only for your open source, non-commercial project so we appreciate your honesty in not moving your company or personal sites there.
 
> If you've already set up a DNS zone for your custom domain on Netlify, you'll also want to move that to this new account following this workflow: https://docs.netlify.com/domains-https/netlify-dns/#transfer-domains-between-teams.
 
> Thanks for all the good your team does in the world!

**Comment by egekorkan** [comment]
@egekorkan will ask the WG/IG for interested ones to join the team

**Comment by egekorkan** [comment]
I have gotten confirmation that I can use this plan in all of the W3C WoT repositories. They should all follow the same guidelines.

**Comment by egekorkan** [comment]
I have sent to the wrong emailing list, a copy will be sent to:
- member-wot-wg@w3.org
- member-wot-ig@w3.org
- group-wot-ie@w3.org

**Comment by egekorkan** [comment]
I have done the transfer and it did not cause anything to break (at least so far). @relu91 @danielpeintner you should see all the settings at https://app.netlify.com/sites/wot-marketing/overview
